import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
        />
      </Head>
        
      <main className={styles.main}>
        <h1 className={styles.title}>
          Company List App
        </h1>

        <p className={styles.description}>
          Explore companies in Blockchain and NFT
        </p>
        <button className='hero__button'>
          <Link href="/companies">Hello</Link>
        </button>
        
         
      </main>

    
      
    </div>
  )
}

export default Home
