import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Company List App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Company List App
        </h1>

        <p className={styles.description}>
          Explore companies in Blockchain and NFT
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Ternoa &rarr;</h2>
            <p>Lorem ipsum is dummy text</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Capsule Corp Labs &rarr;</h2>
            <p>Lorem ipsum is dummy text</p>
          </a>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Polygon &rarr;</h2>
            <p>Lorem ipsum is dummy text</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Solana &rarr;</h2>
            <p>Lorem ipsum is dummy text</p>
          </a>
         
        </div>
      </main>

    
      
    </div>
  )
}

export default Home
